package DSMSApp;


/**
* DSMSApp/DSMSPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dsms.idl
* Sunday, October 18, 2020 7:34:02 o'clock AM EDT
*/

public abstract class DSMSPOA extends org.omg.PortableServer.Servant
 implements DSMSApp.DSMSOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addItem", new java.lang.Integer (0));
    _methods.put ("removeItem", new java.lang.Integer (1));
    _methods.put ("listItemAvailability", new java.lang.Integer (2));
    _methods.put ("purchaseItem", new java.lang.Integer (3));
    _methods.put ("findItem", new java.lang.Integer (4));
    _methods.put ("returnItem", new java.lang.Integer (5));
    _methods.put ("exchangeItem", new java.lang.Integer (6));
    _methods.put ("addWaitList", new java.lang.Integer (7));
    _methods.put ("addCustomerClient", new java.lang.Integer (8));
    _methods.put ("addManagerClient", new java.lang.Integer (9));
    _methods.put ("shutdown", new java.lang.Integer (10));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // DSMSApp/DSMS/addItem
       {
         String managerID = in.read_string ();
         String itemID = in.read_string ();
         String itemName = in.read_string ();
         int quantity = in.read_long ();
         int price = in.read_long ();
         boolean $result = false;
         $result = this.addItem (managerID, itemID, itemName, quantity, price);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // DSMSApp/DSMS/removeItem
       {
         String managerID = in.read_string ();
         String itemID = in.read_string ();
         int quantity = in.read_long ();
         boolean $result = false;
         $result = this.removeItem (managerID, itemID, quantity);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // DSMSApp/DSMS/listItemAvailability
       {
         String managerID = in.read_string ();
         String $result = null;
         $result = this.listItemAvailability (managerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // DSMSApp/DSMS/purchaseItem
       {
         String customerID = in.read_string ();
         String itemID = in.read_string ();
         String dateOfPurchase = in.read_string ();
         String $result = null;
         $result = this.purchaseItem (customerID, itemID, dateOfPurchase);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // DSMSApp/DSMS/findItem
       {
         String customerID = in.read_string ();
         String itemName = in.read_string ();
         String $result = null;
         $result = this.findItem (customerID, itemName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // DSMSApp/DSMS/returnItem
       {
         String customerID = in.read_string ();
         String itemID = in.read_string ();
         String dateOfReturn = in.read_string ();
         boolean $result = false;
         $result = this.returnItem (customerID, itemID, dateOfReturn);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 6:  // DSMSApp/DSMS/exchangeItem
       {
         String customerID = in.read_string ();
         String newitemID = in.read_string ();
         String oldItemID = in.read_string ();
         String dateOfExchange = in.read_string ();
         boolean $result = false;
         $result = this.exchangeItem (customerID, newitemID, oldItemID, dateOfExchange);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 7:  // DSMSApp/DSMS/addWaitList
       {
         String customerID = in.read_string ();
         String itemID = in.read_string ();
         this.addWaitList (customerID, itemID);
         out = $rh.createReply();
         break;
       }

       case 8:  // DSMSApp/DSMS/addCustomerClient
       {
         String customerID = in.read_string ();
         this.addCustomerClient (customerID);
         out = $rh.createReply();
         break;
       }

       case 9:  // DSMSApp/DSMS/addManagerClient
       {
         String managerID = in.read_string ();
         this.addManagerClient (managerID);
         out = $rh.createReply();
         break;
       }

       case 10:  // DSMSApp/DSMS/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:DSMSApp/DSMS:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public DSMS _this() 
  {
    return DSMSHelper.narrow(
    super._this_object());
  }

  public DSMS _this(org.omg.CORBA.ORB orb) 
  {
    return DSMSHelper.narrow(
    super._this_object(orb));
  }


} // class DSMSPOA
