package DSMSApp;


/**
* DSMSApp/DSMS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dsms.idl
* Thursday, October 15, 2020 8:18:26 o'clock PM EDT
*/

public interface DSMS extends DSMSOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DSMS
