package DSMSApp;

/**
* DSMSApp/DSMSHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dsms.idl
* Sunday, October 18, 2020 7:34:02 o'clock AM EDT
*/

public final class DSMSHolder implements org.omg.CORBA.portable.Streamable
{
  public DSMSApp.DSMS value = null;

  public DSMSHolder ()
  {
  }

  public DSMSHolder (DSMSApp.DSMS initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DSMSApp.DSMSHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DSMSApp.DSMSHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DSMSApp.DSMSHelper.type ();
  }

}
