package DSMSApp;


/**
* DSMSApp/DSMS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dsms.idl
* Sunday, October 18, 2020 7:34:02 o'clock AM EDT
*/

public interface DSMS extends DSMSOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DSMS
